#define COLOR_WHITE		  0xFFFFFFFF
#define COLOR_USAGE		  0xF2FF00FF // {F2FF00}
#define COLOR_ERROR       0xbd0000AA // {bd0000}
#define COLOR_SUCCESS     0x04D400AA // {04d400} 
#define COLOR_INFO        0x00a2FFAA  // {00a2ff}  
#define COLOR_WARNING     0xFF8000AA // {ff8000} 
#define COLOR_ADMIN       0xff0011AA // {ff0011}
#define COLOR_SERVER      0xCCCCCCAA // {CCCCCC}

#define MYSQL_HOST "localhost"
#define MYSQL_USER "root"
#define MYSQL_PASS ""
#define MYSQL_DBNAME "tansa"

#define DEFAULT_POS_X 1958.2170 
#define DEFAULT_POS_Y 1343.0073
#define DEFAULT_POS_Z 15.3746
#define DEFAULT_POS_A 268.6832